<?php

/**
 * @file
 * Contains template_whisperer.module.
 */

require_once 'inc/suggestions/page.inc';
require_once 'inc/suggestions/entity.inc';

/**
 * Implements hook_theme_suggestions_alter().
 */
function template_whisperer_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  _template_whisperer_theme_suggestions_page($suggestions, $variables, $hook);
  _template_whisperer_theme_suggestions_entity($suggestions, $variables, $hook);
}

require_once 'inc/rm_cardinality.inc';
require_once 'inc/help.inc';
require_once 'inc/tokens.inc';
require_once 'inc/access.inc';
